application: rj-tilde
version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /favicon\.ico
  static_files: img/favicon.ico
  upload: favicon\.ico

- url: /img/(.*\.(gif|png|jpg|ico))
  static_files: img/\1
  upload: img/(.*\.(gif|png|jpg|ico))


- url: /admin/console/.*
  login: admin
  script: google.appengine.ext.admin.application
  auth_fail_action: unauthorized

- url: /admin/.*
  login: admin
  script: urls.app_admin
  auth_fail_action: unauthorized

- url: .*
  login: required
  script: urls.app


libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: "2.6"


builtins:
- remote_api: on