application: tilde-test
version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: favicon\.ico

- url: /styles
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /images/(.*\.(gif|png|jpg|ico))
  static_files: images/\1
  upload: images/(.*\.(gif|png|jpg|ico))

- url: .*
  login: required
  script: urls.app


libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "2.6"


builtins:
- remote_api: on